# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{validation-sets}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manfred Stienstra"]
  s.date = %q{2010-03-26}
  s.description = %q{A Rails plugin that adds validation sets to Active Record.}
  s.email = %q{manfred@fngtps.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".kick",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/validation_sets.rb",
     "lib/validation_sets/validation_set.rb",
     "rails/init.rb",
     "test/test_helper.rb",
     "test/validation_sets/validation_set_test.rb",
     "test/validation_sets_test.rb",
     "validation-sets.gemspec"
  ]
  s.homepage = %q{http://fingertips.github.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Rails plugin that adds validation sets to Active Record.}
  s.test_files = [
    "test/test_helper.rb",
     "test/validation_sets/validation_set_test.rb",
     "test/validation_sets_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

